name: build

on:
  push:
    branches: [devel]
  pull_request:
    branches: [devel]

jobs:
  build:
    uses: cristalhq/.github/.github/workflows/build.yml@v0.4.0

  vuln:
    uses: cristalhq/.github/.github/workflows/vuln.yml@v0.4.0